name = "Poker"
uuid = "612fdc82-1377-446a-a693-86b197cc4df5"
authors = ["Brian Brewer <bbrewer.email@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
