name = "Poker"
uuid = "612fdc82-1377-446a-a693-86b197cc4df5"
authors = ["Brian Brewer <bbrewer.email@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
PokerIsomorphism_jll = "133beed6-7c83-59bf-b8b3-f5e6e5f3f679"

[compat]
DataDeps = "0.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
